### ISSUE TITLE
Does it work with Ogre 2.1 ?

### ISSUE THREAD

**Issue by mimon** [OGRECave/ogre-procedural#146]
Hello,

I wanted to try this nice library out. Are there support for Ogre 2.1?

**Comment by paroj** [comment]
no, but pull-requests are welcome

**Comment by mimon** [comment]
OK!

I might have a look on it - but my in-depth knowledge is limited. Do you know roughly what, in a couple of bullet points, have to be changed to make it work with 2.1?

**Comment by paroj** [comment]
fixed with #154
