### ISSUE TITLE
build fails for emscripten target against ogre 1.11

### ISSUE THREAD

**Issue by uvguy** [OGRECave/ogre-procedural#148]
Emscripten : 1.37.36
Ogre version : master 

Having small build problem against ogre-procedural master branch, here is the full error log:

[build_error_emscripten.txt](https://github.com/OGRECave/ogre-procedural/files/1863506/build_error_emscripten.txt)

Which sound like emscripten clang problem deducing bool operator against unique_ptr<T> in ogrepass.h.
Related : https://github.com/OGRECave/ogre/issues/716

**Comment by paroj** [comment]
have you tried setting `CMAKE_CXX_FLAGS=-std=c++11` already?

**Comment by uvguy** [comment]
>have you tried setting CMAKE_CXX_FLAGS=-std=c++11 already?

I don't understand why need that. Because std::unique_ptr is valid c++11 code.

**Comment by paroj** [comment]
to explicitly tell clang which C++ version to use. (note ogre 1.11 already does this, ogre-procedural does not)

**Comment by paroj** [comment]
just verified that `-std=c++11` fixed the issue
