### ISSUE TITLE
Remove deleted files from CMake install routines

### ISSUE THREAD

**Issue by KonradNoTantoo** [OGRECave/ogre-procedural#149]
On master, cmake install fails because _CMake/CMakelists.txt_ references files that have been removed from github

`set(INST_FILES
  Packages/FindOIS.cmake
  Packages/FindOGRE.cmake
  Packages/FindOgreProcedural.cmake
  Utils/FindPkgMacros.cmake  
  Utils/PreprocessorUtils.cmake
  Utils/ProceduralConfigTargets.cmake
  Utils/ProceduralMacros.cmake
) `

_Packages/FindOIS.cmake_ and _Packages/FindOGRE.cmake_ are the culprits.

**Comment by paroj** [comment]
can you provide a pull-request?

**Comment by KonradNoTantoo** [comment]
I'm a bit uneducated regarding github usages. Please excuse me.

I'm supposed to fork to be able to commit and produce a PR, is that it?

**Comment by KonradNoTantoo** [comment]
Well, seems I managed to do that by myself. I feel like an adult now.

**Comment by KonradNoTantoo** [comment]
Fork merged, closing issue.
