### ISSUE TITLE
Porting to OGRE 2.2

### ISSUE THREAD

**Issue by TaaTT4** [OGRECave/ogre-procedural#153]
I forked this repository to make the library working with OGRE 2.2. If you create a v2-2 branch (or something similar), I'm more than happy to submit a PR.
In addition, now that `Ogre::ManualObject` has the same features of the historical `Ogre::v1::ManualObject` (see: https://github.com/OGRECave/ogre-next/pull/60) it should be straightforward to support also OGRE 2.1 (from my changes, it should be enough to revert the code I wrote related to `Ogre::Image2` and `Ogre::TextureGpu`).

N.B.: I've ported just the library. Porting the samples and the tests is out of my needs.

**Comment by paroj** [comment]
there you go: https://github.com/OGRECave/ogre-procedural/tree/ogre-next

**Comment by TaaTT4** [comment]
Thanks!

> In addition, now that `Ogre::ManualObject` has the same features of the historical `Ogre::v1::ManualObject` (see: [OGRECave/ogre-next#60](https://github.com/OGRECave/ogre-next/pull/60)) it should be straightforward to support also OGRE 2.1 (from my changes, it should be enough to revert the code I wrote related to `Ogre::Image2` and `Ogre::TextureGpu`).

I hadn't considered that once you build a v2 mesh (e.g. from a v2 manual object) there's no way to generate its tangents. Indeed, the `buildTangentVectors` exists just in v1 `Mesh` class. So, it's probably better to keep staying with v1 manual objects/meshes even if OGRE 2.2 is used. In this way, the user will have afterwards the freedom to decide what to do with the procedurally generated geometries: post-process them (e.g. building tangents, generating LODs, etc) or import them in v2 meshes.
